rename password to key to clarify its content

diff --git a/decode_secret b/decode_secret
--- a/decode_secret
+++ b/decode_secret
@@ -69,9 +69,9 @@ if [ $(( ${#value} % 8 )) -ne 0 ]; then
 	printf "The specified encoded value has a wrong length.\n" "$serial" 1>&2
 	exit 1
 fi
-password="$2"
-if [ ${#password} -ne 32 ] && [ ${#password} -ne 64 ]; then
-	printf "The specified password '%s' looks bad. It should contain exactly 32 or 64 hexadecimal digits and will be padded with zeroes to 32 bytes.\n" "$password" 1>&2
+key="$2"
+if [ ${#key} -ne 32 ] && [ ${#key} -ne 64 ]; then
+	printf "The specified key '%s' looks bad. It should contain exactly 32 or 64 hexadecimal digits and will be padded with zeroes to 32 bytes.\n" "$key" 1>&2
 	exit 1
 fi
 #######################################################################################################
@@ -94,7 +94,7 @@ val="$(expr "$hexval" : ".\{32\}\(.*\)")"
 #                                                                                                     #
 #######################################################################################################
 [ $(( ${#val} % 32 )) -eq 0 ] && val="${val}00"
-decval="$(printf "%s\n" "$val" | yf_hex2bin | openssl enc -d -aes256 -K $password -iv $iv 2>/dev/null | yf_bin2hex)"
+decval="$(printf "%s\n" "$val" | yf_hex2bin | openssl enc -d -aes256 -K $key -iv $iv 2>/dev/null | yf_bin2hex)"
 #######################################################################################################
 #                                                                                                     #
 # split the result into hash and hashed content and recompute the hash                                #
@@ -104,7 +104,7 @@ hash="$(expr "$decval" : "\(.\{8\}\).*")"
 valbuf="$(expr "$decval" : ".\{8\}\(.*\)")"
 valhash="$(expr "$(printf "%s\n" "$valbuf" | yf_hex2bin | openssl dgst -md5 -binary 2>/dev/null | yf_bin2hex)" : "\(.\{8\}\).*")"
 if ! [ "$hash" = "$valhash" ]; then
-	printf "Error decoding value, please check the specified password.\n" 1>&2
+	printf "Error decoding value, please check the specified key.\n" 1>&2
 	[ $debug -ne 1 ] && exit 1
 	rc=1
 else
@@ -126,14 +126,14 @@ else
 #######################################################################################################
 fi
 if [ $debug -eq 1 ]; then
-	printf "password  : (%03u) %s\n" $(( ${#password} / 2 )) "$password" 1>&2
-	printf "input     : (%03u) %s\n" $(( ${#hexval} / 2 )) "$hexval" 1>&2
-	printf "iv        : (%03u) %s\n" $(( ${#iv} / 2 )) "$iv" 1>&2
-	printf "encoded   : (%03u) %s\n" $(( ${#val} / 2 )) "$val" 1>&2
-	printf "decoded   : (%03u) %s\n" $(( ${#decval} / 2 )) "$decval" 1>&2
-	printf "hmac      : (%03u) %s\n" $(( ${#hash} / 2 )) "$hash" 1>&2
-	printf "length    :  %03u\n" "$len" 1>&2
-	printf "cleartext : (%03u) %s\n" $(( ${#decoded} / 2 )) "$decoded" 1>&2
+	printf "key    : (%03u) %s\n" $(( ${#key} / 2 )) "$key" 1>&2
+	printf "input  : (%03u) %s\n" $(( ${#hexval} / 2 )) "$hexval" 1>&2
+	printf "iv     : (%03u) %s\n" $(( ${#iv} / 2 )) "$iv" 1>&2
+	printf "encoded: (%03u) %s\n" $(( ${#val} / 2 )) "$val" 1>&2
+	printf "decoded: (%03u) %s\n" $(( ${#decval} / 2 )) "$decval" 1>&2
+	printf "hmac   : (%03u) %s\n" $(( ${#hash} / 2 )) "$hash" 1>&2
+	printf "length :  %03u\n" "$len" 1>&2
+	printf "clear  : (%03u) %s\n" $(( ${#decoded} / 2 )) "$decoded" 1>&2
 else
 	printf "%s\n" "$decoded" | yf_hex2bin
 fi
