isolate OpenSSL and YourFritz script library calls in a single script

diff --git a/decode_secret b/decode_secret
--- a/decode_secret
+++ b/decode_secret
@@ -1,4 +1,5 @@
 #! /bin/sh
+# vim: set tabstop=4 syntax=sh :
 #######################################################################################################
 #                                                                                                     #
 # decode a single encrypted value, which was encoded by AVM's cipher algorithm                        #
@@ -24,120 +25,92 @@
 # If decoding was successful, the decoded value is written to STDOUT. If it contains a C-style string #
 # value (the last byte is NUL), the end-of-string character is cut off.                               #
 #                                                                                                     #
-# This script needs an OpenSSL binary with the 'dgst' function (for MD5 hashes) and knowledge of the  #
-# AES-256 (CBC) encryption mode, which will be used with the 'enc -d' function.                       #
-# For data conversion, the YourFritz shell script library is needed.                                  #
-#                                                                                                     #
 #######################################################################################################
 #                                                                                                     #
 # check debug option                                                                                  #
 #                                                                                                     #
 #######################################################################################################
+nooutput=0
 if [ "$1" = "-d" -o "$1" = "--debug" ]; then
 	debug=1
-	# ATTENTION: No output will be written to STDOUT - this is for 'test mode' only
+	dbg="-d"
+	shift
+elif [ "$1" = "-D" -o "$1" = "--debug-only" ]; then
+	debug=1
+	nooutput=1
+	dbg="-d"
 	shift
 else
 	debug=0
 fi
 #######################################################################################################
 #                                                                                                     #
-# subfunctions                                                                                        #
-#                                                                                                     #
-#######################################################################################################
-#                                                                                                     #
-# import the needed functions from the YourFritz script library                                       #
-#                                                                                                     #
-#######################################################################################################
-if [ -f "$0.yf_scriptlib" ]; then
-	. $0.yf_scriptlib
-else
-	YF_SCRIPT_FUNCTIONS="yf_base32_decode yf_bin2hex yf_hex2bin yf_hex2dec"
-	YF_SCRIPT_SAVE=1
-	. "$YF_SCRIPT_DIR/yf_helpers"
-fi
-#######################################################################################################
-#                                                                                                     #
 # check parameters                                                                                    #
 #                                                                                                     #
 #######################################################################################################
+if [ "$1" = "-x" -o "$1" = "--hex-output" ]; then
+	hexoutput=1
+	shift
+else
+	hexoutput=0
+fi
 if [ $# -ne 2 ]; then
-	printf "Missing at least one argument, please read the description from the comment block at the beginning of this script file.\n" 1>&2
+	printf "Missing at least one argument, we need the cipher text (Base32) and a key.\n" 1>&2
 	exit 1
 fi
-value="$1"
+base32="$1"
 if [ $(( ${#value} % 8 )) -ne 0 ]; then
 	printf "The specified encoded value has a wrong length.\n" "$serial" 1>&2
 	exit 1
 fi
 key="$2"
 if [ ${#key} -ne 32 ] && [ ${#key} -ne 64 ]; then
-	printf "The specified key '%s' looks bad. It should contain exactly 32 or 64 hexadecimal digits and will be padded with zeroes to 32 bytes.\n" "$key" 1>&2
+	printf "The specified key '%s' looks bad. It should contain exactly 32 or 64 hexadecimal\ndigits and will be padded with zeroes to 32 bytes.\n" "$key" 1>&2
 	exit 1
 fi
 #######################################################################################################
 #                                                                                                     #
-# decode the encoded value from Base32 presentation to hexadecimal string and split it into IV and    #
-# encoded value                                                                                       #
+# try to decrypt the value                                                                            #
 #                                                                                                     #
 #######################################################################################################
-hexval="$(printf "%s\n" "$value" | yf_base32_decode | yf_bin2hex)"
-iv="$(expr "$hexval" : "\(.\{32\}\).*")"
-val="$(expr "$hexval" : ".\{32\}\(.*\)")"
-#######################################################################################################
-#                                                                                                     #
-# decode the buffer with OpenSSL binary, this will usually throw an error due to invalid length of    #
-# last block, if cleartext size wasn't between 39 and 54 byte, which results in a complete block of   #
-# data for the last round of decoding                                                                 #
-# remark: because the call to 'EVP_DecryptFinal_ex' fails with 'bad decrypt' in case of a last buffer #
-# with a full block to decode, we add some junk and the last round will complete without problems,    #
-# before the final block fails with 'wrong final block length'                                        #
-#                                                                                                     #
-#######################################################################################################
-[ $(( ${#val} % 32 )) -eq 0 ] && val="${val}00"
-decval="$(printf "%s\n" "$val" | yf_hex2bin | openssl enc -d -aes256 -K $key -iv $iv 2>/dev/null | yf_bin2hex)"
-#######################################################################################################
-#                                                                                                     #
-# split the result into hash and hashed content and recompute the hash                                #
-#                                                                                                     #
-#######################################################################################################
-hash="$(expr "$decval" : "\(.\{8\}\).*")"
-valbuf="$(expr "$decval" : ".\{8\}\(.*\)")"
-valhash="$(expr "$(printf "%s\n" "$valbuf" | yf_hex2bin | openssl dgst -md5 -binary 2>/dev/null | yf_bin2hex)" : "\(.\{8\}\).*")"
-if ! [ "$hash" = "$valhash" ]; then
-	printf "Error decoding value, please check the specified key.\n" 1>&2
-	[ $debug -ne 1 ] && exit 1
-	rc=1
-else
-#######################################################################################################
-#                                                                                                     #
-# compute the hash now                                                                                #
-#                                                                                                     #
-#######################################################################################################
-	rc=0
-	len="$(yf_hex2dec "$(expr "$valbuf" : "\(.\{8\}\).*")")"
-	if [ "$(expr "$valbuf" : ".\{$(( ( 4 + len - 1 ) * 2 ))\}\(..\).*")" = "00" ]; then
-		len=$(( len - 1 ))
+[ $debug -eq 1 ] && printf "key\t: (%03u) 0x%s\n" $(( ${#key} / 2 )) "$key" 1>&2
+[ $debug -eq 1 ] && printf "base32\t: (%03u) %s\n" ${#base32} "$base32" 1>&2
+encoded="$(printf "%s\n" "$base32" | crypto b32dec)"
+[ $debug -eq 1 ] && printf "input\t: (%03u) 0x%s\n" $(( ${#encoded} / 2 )) "$encoded" 1>&2
+iv="$(expr "$encoded" : "\(.\{32\}\).*")"
+encoded="$(expr "$encoded" : ".\{32\}\(.*\)")"
+[ $debug -eq 1 ] && printf "iv\t: (%03u) 0x%s\n" $(( ${#iv} / 2 )) "$iv" 1>&2
+[ $debug -eq 1 ] && printf "enc'd\t: (%03u) 0x%s\n" $(( ${#encoded} / 2 )) "$encoded" 1>&2
+encoded="${encoded}00"
+decoded="$(printf "%s" "$encoded" | crypto aes_decrypt "$key" "$iv")"
+[ $debug -eq 1 ] && printf "dec'd\t: (%03u) 0x%s\n" $(( ${#decoded} / 2 )) "$decoded" 1>&2
+hash="$(expr "$decoded" : "\(.\{8\}\).*")"
+#[ $debug -eq 1 ] && printf "hash\t: (%03u) %s\n" ${#hash} "$hash" 1>&2
+hexsize="$(expr "$decoded" : ".\{8\}\(.\{8\}\).*")"
+value="$(expr "$decoded" : ".\{16\}\(.*\)")"
+size=$(printf "%s\n" "$hexsize" | crypto hex2dec)
+[ $debug -eq 1 ] && printf "size\t: %u\n" $size 1>&2
+if [ $size -le $(( ${#value} / 2 )) ]; then
+	vhash="$(printf "%s%s\n" "$hexsize" "$value" | crypto digest -x)"
+	verify="$(expr "$vhash" : "\(.\{8\}\).*")"
+	if [ "$hash" = "$verify" ]; then
+		[ $hexoutput -eq 0 ] && size=$(( size - 1 ))
+		value="$(expr "$value" : "\(.\{$(( size * 2 ))\}\).*")"
+		[ $hexoutput -eq 0 ] && value="$(printf "%s\n" "$value" | crypto hexdec)"
+		if [ $debug -eq 1 ]; then
+			printf "value\t: (%03u) " $size 1>&2
+			[ $hexoutput -eq 1 ] && printf "0x" 1>&2
+			printf "%s\n" $value 1>&2
+		fi
+		[ $nooutput -ne 1 ] && printf "%s\n" "$value"
+		exit 0
+	else
+		[ $debug -eq 1 ] && printf "to hash\t: (%03u) 0x%s %s\n" $(( ( ${#hexsize} + ${#value} ) / 2 )) "$hexsize" "$value" 1>&2
+		[ $debug -eq 1 ] && printf "hash\t: (%03u) 0x%s\n" $(( ${#vhash} / 2 )) "$vhash" 1>&2
 	fi
-	decoded="$(expr "$valbuf" : ".\{8\}\(.\{$(( len * 2 ))\}\).*")"
-#######################################################################################################
-#                                                                                                     #
-# write the decoded data to STDOUT                                                                    #
-#                                                                                                     #
-#######################################################################################################
 fi
-if [ $debug -eq 1 ]; then
-	printf "key    : (%03u) %s\n" $(( ${#key} / 2 )) "$key" 1>&2
-	printf "input  : (%03u) %s\n" $(( ${#hexval} / 2 )) "$hexval" 1>&2
-	printf "iv     : (%03u) %s\n" $(( ${#iv} / 2 )) "$iv" 1>&2
-	printf "encoded: (%03u) %s\n" $(( ${#val} / 2 )) "$val" 1>&2
-	printf "decoded: (%03u) %s\n" $(( ${#decval} / 2 )) "$decval" 1>&2
-	printf "hmac   : (%03u) %s\n" $(( ${#hash} / 2 )) "$hash" 1>&2
-	printf "length :  %03u\n" "$len" 1>&2
-	printf "clear  : (%03u) %s\n" $(( ${#decoded} / 2 )) "$decoded" 1>&2
-else
-	printf "%s\n" "$decoded" | yf_hex2bin
-fi
+[ $debug -eq 1 ] && printf "Error decoding value with the specified key.\a\n" 1>&2
+exit 1
 #######################################################################################################
 #                                                                                                     #
 # no housekeeping needed                                                                              #
diff --git a/password_from_device b/password_from_device
--- a/password_from_device
+++ b/password_from_device
@@ -1,4 +1,5 @@
 #! /bin/sh
+# vim: set tabstop=4 syntax=sh :
 #######################################################################################################
 #                                                                                                     #
 # read the variables for the device password from the 'urlader environment' and compute the device    #
@@ -24,46 +25,62 @@
 # If the option '-e' (or '--export') is specified, a hash value to be used as export password is      #
 # computed (it contains less device specific values).                                                 #
 #                                                                                                     #
-# This script needs an OpenSSL binary with the 'dgst' function and MD5 support for it and another     #
-# script (device_password) to compute the hash (the OpenSSL binary will be called from there).        #
-# The computed hash value is written to STDOUT (in binary format), the caller is responsible for the  #
-# proper redirection.                                                                                 #
-#                                                                                                     #
 #######################################################################################################
 #                                                                                                     #
 # constants                                                                                           #
 #                                                                                                     #
 #######################################################################################################
-#urlader_environment="/proc/sys/urlader/environment"
-urlader_environment="/var/env"
+urlader_environment="/proc/sys/urlader/environment"
+alternative_environment="/var/env" # AVM stores a copy here at boot time
 serial_name="SerialNumber"
 maca_name="maca"
 wlan_key_name="wlan_key"
 tr069_pw_name="tr069_passphrase"
-needed_scripts="device_password"
+needed_scripts="device_password crypto"
 #######################################################################################################
 #                                                                                                     #
-# check debug option                                                                                  #
+# check options                                                                                       #
 #                                                                                                     #
 #######################################################################################################
-if [ "$1" = "-d" -o "$1" = "--debug" ]; then
-	debug=1
-	shift
-else
-	debug=0
-fi
+export=0
+debug=0
+while [ $# -gt 0 ]; do
+	case "$1" in
+		("-d" | "--debug")
+			debug=1
+			dbg="-d"
+			shift
+			;;
+		("-e" | "--export")
+			export=1
+			shift
+			;;
+		("-a" | "--alt-environ")
+			if [ ${#2} -eq 0 ]; then
+				printf "Missing file name after '%s' option.\n" "$1" 1>&2
+				exit 1
+			fi
+			alternative_environment="$2"
+			shift 2
+			;;
+		(*)
+			printf "Invalid parameter/option '%s' found on command line.\n" "$1" 1>&2
+			exit 1
+			;;
+	esac
+done
 #######################################################################################################
 #                                                                                                     #
 # check environment                                                                                   #
 #                                                                                                     #
 #######################################################################################################
-if [ -t 1 ]; then
-	printf "Please redirect STDOUT of this script, the computed key will be written in binary to this handle.\n" 1>&2
+if ! [ -f "$urlader_environment" ] && ! [ -f "$alternative_environment" ]; then
+	printf "Neither the file '%s' nor the alternative '%s' exist.\n" "$urlader_environment" "$alternative_environment" 1>&2
 	exit 1
-fi
-if ! [ -f "$urlader_environment" ]; then
-	printf "File '%s' does not exist.\n" "$urlader_environment" 1>&2
-	exit 1
+elif ! [ -f "$urlader_environment" ]; then
+	env="$alternative_environment"
+else
+	env="$urlader_environment"
 fi
 [ "$(expr "$0" : ".*\(/\).*")" = "/" ] && d="${0%/*}" || d="."
 for n in $needed_scripts; do
@@ -76,32 +93,29 @@ for n in $needed_scripts; do
 done
 #######################################################################################################
 #                                                                                                     #
-# check export option                                                                                 #
-#                                                                                                     #
-#######################################################################################################
-if [ "$1" = "-e" -o "$1" = "--export" ]; then
-	export=1
-	shift
-else
-	export=0
-fi
-#######################################################################################################
-#                                                                                                     #
 # read data from environment                                                                          #
 #                                                                                                     #
 #######################################################################################################
-serial="$(sed -n -e "s|^$serial_name[ \t]*\(.*\)\$|\1|p" "$urlader_environment")"
-maca="$(sed -n -e "s|^$maca_name[ \t]*\(.*\)\$|\1|p" "$urlader_environment")"
+serial="$(sed -n -e "s|^$serial_name[ \t]*\(.*\)\$|\1|p" "$env")"
+[ $debug -eq 1 ] && printf "found serial number '%s'\n" "$serial" 1>&2
+maca="$(sed -n -e "s|^$maca_name[ \t]*\(.*\)\$|\1|p" "$env")"
+[ $debug -eq 1 ] && printf "found maca value '%s'\n" "$maca" 1>&2
 if [ $export -eq 0 ]; then
-	wlan_key="$(sed -n -e "s|^$wlan_key_name[ \t]*\(.*\)\$|\1|p" "$urlader_environment")"
-	tr069_passphrase="$(sed -n -e "s|^$tr069_pw_name[ \t]*\(.*\)\$|\1|p" "$urlader_environment")"
+	wlan_key="$(sed -n -e "s|^$wlan_key_name[ \t]*\(.*\)\$|\1|p" "$env")"
+	[ $debug -eq 1 ] && printf "found WLAN key '%s'\n" "$wlan_key" 1>&2
+	tr069_passphrase="$(sed -n -e "s|^$tr069_pw_name[ \t]*\(.*\)\$|\1|p" "$env")"
+	if [ $debug -eq 1 ]; then
+		[ ${#tr069_passphrase} -gt 0 ] && \
+			 printf "found TR-069 passphrase '%s'\n" "$tr069_passphrase" 1>&2 || \
+			 printf "no TR-069 passphrase found\n" 1>&2
+	fi
 fi
 #######################################################################################################
 #                                                                                                     #
 # compute the hash now                                                                                #
 #                                                                                                     #
 #######################################################################################################
-$device_password $serial $maca $wlan_key $tr069_passphrase
+$device_password $dbg $serial $maca $wlan_key $tr069_passphrase
 exit $?
 #######################################################################################################
 #                                                                                                     #
