print to STDERR unconditionally

diff --git a/device_password b/device_password
--- a/device_password
+++ b/device_password
@@ -59,34 +59,34 @@ fi
 #                                                                                                     #
 #######################################################################################################
 if [ -t 1 ]; then
-	[ $debug -eq 1 ] && printf "Please redirect STDOUT of this script, the computed key will be written in binary to this handle.\n" 1>&2
+	printf "Please redirect STDOUT of this script, the computed key will be written in binary to this handle.\n" 1>&2
 	exit 1
 fi
 if [ $# -lt 2 ]; then
-	[ $debug -eq 1 ] && printf "Missing at least one argument, please read the description from the comment block at the beginning of this script file.\n" 1>&2
+	printf "Missing at least one argument, please read the description from the comment block at the beginning of this script file.\n" 1>&2
 	exit 1
 fi
 if ! openssl dgst -md5 -binary </dev/null 2>/dev/null 1>&2; then
-	[ $debug -eq 1 ] && printf "Error calling OpenSSL to create a MD5 hash. Please check, if 'openssl' is present and supports the needed function.\n" 1>&2
+	printf "Error calling OpenSSL to create a MD5 hash. Please check, if 'openssl' is present and supports the needed function.\n" 1>&2
 	exit 1
 fi
 serial="$1"
 if [ ${#serial} -ne 16 ]; then
-	[ $debug -eq 1 ] && printf "The specified serial number '%s' should contain exactly 16 characters.\n" "$serial" 1>&2
+	printf "The specified serial number '%s' should contain exactly 16 characters.\n" "$serial" 1>&2
 	exit 1
 fi
 maca="$2"
 if [ ${#maca} -ne 17 ]; then
-	[ $debug -eq 1 ] && printf "The specified MAC address '%s' should contain exactly 17 characters.\n" "$maca" 1>&2
+	printf "The specified MAC address '%s' should contain exactly 17 characters.\n" "$maca" 1>&2
 	exit 1
 fi
 wlan_key="$3"
 if [ ${#wlan_key} -gt 0 ] && [ ${#wlan_key} -ne 16 ] && [ ${#wlan_key} -ne 20 ]; then
-	[ $debug -eq 1 ] && printf "A correct WLAN key contains 16 or 20 (decimal) numbers, you specified this one: '%s'.\n" "$wlan_key" 1>&2
+	printf "A correct WLAN key contains 16 or 20 (decimal) numbers, you specified this one: '%s'.\n" "$wlan_key" 1>&2
 	exit 1
 fi
 if ! [ "$(expr "$maca" : "\([A-F0-9:]*\)")" = "$maca" ]; then
-	[ $debug -eq 1 ] && printf "The specified MAC address '%s' contains unexpected characters.\n" "$maca" 1>&2
+	printf "The specified MAC address '%s' contains unexpected characters.\n" "$maca" 1>&2
 	exit 1
 fi
 #######################################################################################################
